# -*- coding: utf-8 -*-
"""Association Rules.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U81MX-VTT5Wz3WR3y9q6WeYdnviaqWaC
"""

import pandas as pd
from mlxtend.frequent_patterns import apriori, association_rules
from mlxtend.preprocessing import TransactionEncoder

from google.colab import drive
drive.mount('/content/drive')

file_name = "/content/Titanic.csv"

titanic = pd.read_csv(file_name)
titanic

df=pd.get_dummies(titanic)
df.head()

frequent_itemsets = apriori(df, min_support=0.1, use_colnames=True)
frequent_itemsets

rules = association_rules(frequent_itemsets, metric="lift", min_threshold=0.7)
rules

rules.sort_values('lift',ascending = False)[0:20]