# -*- coding: utf-8 -*-
"""Data_Cleaning_Inputations.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IR1mq80lds6gjls2H_abd4nGTt2F2W5A
"""

import pandas as pd
import numpy as np

# Create a dictionary 'data' to store our data
data = {
    'square_feet_area': [8500, 9600, np.nan, 11250, np.nan, 9550, 14260, np.nan, 13830, 11500],
    'Year_built': [2003, 1976, 2001, np.nan, 1988, 2000, 2006, 1978, 1950, np.nan],
    'over_all_condition': [5, 8, 6, 7, np.nan, 7, 8, 6, np.nan, 7],
    'ready_to_move': ['Yes', 'No', 'No', np.nan, 'No', np.nan, 'Yes', 'Yes', 'No', 'Yes'],
    'Sale_price': [200000, 100000, 300000, 210000, 3100000, 51000000]
}

# Create a pandas DataFrame from the 'data' dictionary
# Instead of directly passing the dictionary 'data', I create separate Series for each column and then combine them into a DataFrame.
df = pd.DataFrame({
    'square_feet_area': pd.Series(data['square_feet_area']),
    'Year_built': pd.Series(data['Year_built']),
    'over_all_condition': pd.Series(data['over_all_condition']),
    'ready_to_move': pd.Series(data['ready_to_move']),
    'Sale_price': pd.Series(data['Sale_price'])
})


print("Original DataFrame:")
print(df)

# Fill missing values
df['square_feet_area'].fillna(df['square_feet_area'].mean(), inplace=True)
df['Year_built'].fillna(df['Year_built'].mean(), inplace=True)
df['over_all_condition'].fillna(df['over_all_condition'].mean(), inplace=True)
df['ready_to_move'].fillna(df['ready_to_move'].mode()[0], inplace=True)

print("\nDataFrame after handling missing values with mean (for numeric) and mode (for category):")
print(df)

# Create a pandas DataFrame from the 'data' dictionary
# Instead of directly passing the dictionary 'data', I create separate Series for each column and then combine them into a DataFrame.
df = pd.DataFrame({
    'square_feet_area': pd.Series(data['square_feet_area']),
    'Year_built': pd.Series(data['Year_built']),
    'over_all_condition': pd.Series(data['over_all_condition']),
    'ready_to_move': pd.Series(data['ready_to_move']),
    'Sale_price': pd.Series(data['Sale_price'])
})


print("Original DataFrame:")
print(df)

# Fill missing values
df['square_feet_area'].fillna(df['square_feet_area'].mean(), inplace=True)
df['Year_built'].fillna(df['Year_built'].mean(), inplace=True)
df['over_all_condition'].fillna(df['over_all_condition'].mean(), inplace=True)
df['ready_to_move'].fillna(df['ready_to_move'].mode()[0], inplace=True)

print("\nDataFrame after handling missing values with mean (for numeric) and mode (for category):")
print(df)