# -*- coding: utf-8 -*-
"""Multi linear Regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L2SH3F5pfHtAKlwFoBJciNUZZVEaV03S
"""

import pandas as pd

from google.colab import files
uploaded = files.upload()

file_name = list(uploaded.keys())[0]

df = pd.read_csv(file_name)

print(df.head())

print(df)

import statsmodels.formula.api as smf
model = smf.ols('MPG~WT+VOL+SP+HP',data=df).fit()

model.params

print(model.tvalues,'\n',model.pvalues)

(model.rsquared,model.rsquared_adj)

ml_v=smf.ols('MPG~VOL',data=df).fit()
print(ml_v.tvalues,'\n',ml_v.pvalues)

(ml_v.rsquared,ml_v.rsquared_adj)

ml_w=smf.ols('MPG~WT',data=df).fit()
print(ml_w.tvalues,'\n',ml_w.pvalues)

(ml_w.rsquared,ml_w.rsquared_adj)

ml_wv=smf.ols('MPG~WT+VOL',data=df).fit()
print(ml_wv.tvalues,'\n',ml_wv.pvalues)

def get_standardized_values( vals ):
  return (vals - vals.mean())/vals.std()

model_influence = model.get_influence()
(c, _) = model_influence.cooks_distance

cars[cars.index.isin([70, 76])]

cars.head()

car1=cars_new.drop(cars_new.index[[70, 76]],axis=0).reset_index()

car1=car1.drop(['index'],axis=1)

"""car1"""

final_mlV= smf.ols('MPG~VOL+SP+HP',data = car1).fit()

(final_ml_V.rsquared,final_ml_V.aic)

model_influence = final_mlV.get_influence()
(c_v,_) = model_influence.cooks_distance

