# -*- coding: utf-8 -*-
"""scatter_plots.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v__XBOk7KypWJLoKJ5SPeHtZ0TWGkvsr
"""

import pandas as pd
import matplotlib.pyplot as plt

data = {
    'Day': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    'Stock_A_returns': [0.02, 0.03, -0.01, 0.04, -0.03, 0.01, 0.05, 0.02, -0.02, 0.01],
    'Stock_B_returns': [0.01, -0.02, 0.04, 0.03, 0.02, -0.01, 0.04, 0.01, 0.02, 0.01]
}

df = pd.DataFrame(data)

plt.figure(figsize=(8, 6))
plt.scatter(df['Stock_A_returns'], df['Stock_B_returns'], color='blue', label='Returns Comparison')

plt.title('Stock A vs Stock B Returns')
plt.xlabel('Stock A Returns', fontsize=12)
plt.ylabel('Stock B Returns', fontsize=12)

plt.grid(True)
plt.legend()

plt.show()

import statistics
import numpy as np

stock_prices = [100, 102, 98, 105, 101, 97, 99, 103, 100, 98]

variance = statistics.variance(stock_prices)
print(f"Variance of stock prices: {variance}")

numpy_variance = np.var(stock_prices, ddof=1) #ddof = 1 for sample variance
print(f"Variance of stock prices (using NumPy) : {numpy_variance}" )

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

data = {
    'Temp': [30, 22, 28, 35, 33, 25, 27, 32, 31],
    'Humidity': [60, 65, 55, 40, 45, 70, 50, 60, 55],
    'Wind speed': [10, 12, 18, 17, 18, 16, 14, 11, 19],  # Fixed length to match others
    'Pressure': [1015, 1017, 1019, 1016, 1013, 1012, 1011, 1018, 1012]
}

df = pd.DataFrame(data)

# Scatter plot Temp vs Humidity
plt.figure(figsize=(8,6))
plt.scatter(df['Temp'], df['Humidity'], color='blue', label='Temp vs Humidity')
plt.title('Temp vs Humidity')
plt.xlabel('Temp')
plt.ylabel('Humidity')
plt.grid(True)
plt.legend()

# Pairplot without the 'hue' argument
sns.pairplot(df)
plt.show()

