# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eJ6YlcZgpfMCiV03Hlj5ZC_y6U8TC3WY
"""

import matplotlib.pyplot as plt
data = [5, 7, 7,8,9,10,10,10,11,12,11,11]
plt.hist(data, bins = 10, edgecolor = 'black')
plt.title('Simple Histogram Example')
plt.xlabel('Value')
plt.ylabel('Count')
plt.show()
plt.ylabel('Count')
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Create a Pandas DataFrame
datf = pd.DataFrame({"Season 1": [7, 4, 5, 6, 3],
                      "Season 2": [1, 2, 8, 4, 9]})

# Create the histogram using Seaborn
p = sns.histplot(data=datf)

# Set the labels for the x and y axes
p.set(xlabel="X Label Value", ylabel="Y Label Value")

# Display the plot
plt.show()

import matplotlib.pyplot as plt
import numpy as np
import matplotlib.pyplot as plt
import numpy as np
np.random.seed(42)
data = np.random.randint(20,80,1000)
plt.hist(data, bins = 20, edgecolor = 'black', color='lavender')
plt.title('Histogram of Cancer Patience Age Distribution')
plt.xlabel('Age')
plt.ylabel('Number of Patience')
plt.show()
plt.ylabel('Number of Patience')
plt.show()

